import express from "express";
import User from "../models/userSchema.js";
import jwt from "jsonwebtoken";
// npm i bcryptjs to install bcrypt to be able to do client-side hashing, allowing secure password handling 
import bcrypt from "bcryptjs";
import dotenv from "dotenv";
// install express-validator
// check function defines validation rules for specific fields
// validationResult is used within the route handler to collect and handle any errors generated by the check() rules 
import { check, validationResult } from "express-validator";
dotenv.config();

const router = express.Router();

router.route("/")
.post(
    [
        // establish validation rules for name, email & password
        check("name", "Name is required.").not().isEmpty(),
        check("email", "Please include a valid email").isEmail(),
        check("password",
            "Please enter a password with 6 or more characters.",
        ).isLength({ min: 6 })
    ],
    async (req, res) => {
        // create a variable to hold errors and store in an array from previous "checks"

        const errors = validationResult(req);

        // if errors array is NOT empty, res w/ error
        if(!errors.isEmpty())
            return res.status(400).json({ errors: errors.array() });

        // create array obj to store errors in
        const { name, email, password } = req.body;

        try {
            // check if user already exists
            let user = await User.findOne({ email });

            // res w/ error 
            if (user)
                return res.status(400).json({ errors: [{ msg: "User already exists" }] });

            // create new user obj
            user = new User({
                name, 
                email,
                password,
            });

            // create salt to hash pw. Num represents number of rounds of encryption, typically btw 10-12
            const salt = await bcrypt.genSalt(10);
            
            // hash/encrypt our pw
            user.password = await bcrypt.hash(password, salt);


            // save user to DB
            await user.save();

            // create payload for JWT
            const payload = {
                user: {
                    id: user._id,
                    name: user.name, //usually wouldnt include bc bloats token and for security but since we're connecting to FE display its ok here
                },
            };

            //Res w/JWT, bc we are registering and logging in simultaneously
            jwt.sign(
                payload,
                process.env.jwtSecret,
                { expiresIn: "3h" },
                (err, token) => {
                    if (err) throw err;

                    res.json({ token });
                },
            );
        } catch (err) {
            console.error(err.message);
            res.status(err.status || 500)
            .json({ errors: [{ msg: `❌ Error: ${err.message}`}] });
        }
    },
);

export default router;